# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'

# Commands
"command: backup":
  - "(command: backup)"
"command: console":
  - "(command: console|tmux)"
"command: debug":
  - "(command: debug)"
"command: details":
  - "(command: details)"
"command: fast-dl":
  - "(command: fast-dl|fastdl|fast-dl)"
"command: install":
  - "(command: install)"
"command: mods":
  - "(command: mods)"
"command: monitor":
  - "(command: monitor|monitor)"
"command: post-details":
  - "(command: post-details|post-details)"
"command: restart":
  - "(command: restart)"
"command: send":
  - "(command: send)"
"command: skeleton":
  - "(command: skeleton)"
"command: start":
  - "(command: start)"
"command: stop":
  - "(command: stop)"
"command: update-lgsm":
  - "(command: update-lgsm|update-lgsm)"
"command: update":
  - "(command: update)"
"command: validate":
  - "(command: validate)"
"command: wipe":
  - "(command: wipe)"
# Distros
"distro: AlmaLinux":
  - "(Alma)"
"distro: Arch Linux":
  - "(Arch)"
"distro: CentOS":
  - "(CentOS)"
"distro: Debian":
  - "(Debian)"
"distro: Fedora":
  - "(Fedora)"
"distro: openSUSE":
  - "(openSUSE|suse)"
"distro: Rocky Linux":
  - "(Rocky)"
"distro: Slackware":
  - "(Slackware)"
"distro: Ubuntu":
  - "(Ubuntu)"
# Games
"game: Ark: Survival Evolved":
  - "(Ark: Survival Evolved|Ark)"
"game: ARMA 3":
  - "(ARMA 3)"
"game: Assetto Corsa":
  - "(Assetto Corsa)"
"game: Avorion":
  - "(Avorion)"
"game: Ballistic Overkill":
  - "(Ballistic Overkill)"
"game: Barotrauma":
  - "(Barotrauma)"
"game: Black Mesa":
  - "(Black Mesa)"
# Info
"info: alerts":
  - "(alert)"
"info: dependency":
  - "(dependency|deps)"
"info: docker":
  - "(docker)"
"info: docs":
  - "(documentation|docs)"
"info: email":
  - "(postfix|sendmail|exim|smtp)"
"info: query":
  - "(gamedig|gsquery)"
"info: steamcmd":
  - "(steamcmd)"
"info: systemd":
  - "(systemd)"
"info: tmux":
  - "(tmux)"
"info: website":
  - "(website)"
# Type
"type: game server request":
  - "(Server Request)"
"type: bug":
  - "(bug)"
"type: feature request":
  - "(feature)"
